### ISSUE TITLE
Quelques posts en md dans la src ?

### ISSUE THREAD

**Issue by nlebellier** [jeromecoupe/eleventy_starter#8]
re bonjour,
Dommage que tu ne fournisses pas quelques md dans le dossier blog pour illustrer le fonctionnement de la partie blog...
C'est prévu ou un oubli ?

**Comment by jeromecoupe** [comment]
J'ai ajouté qq blogposts, pagination, etc

**Comment by jeromecoupe** [comment]
This starter was originally just for me to start projects quicker. Apart from the basic setup (NPM scripts, etc) I don't use it that much but left it there so others can use it. Glad you checked it out ;o)

**Comment by nlebellier** [comment]
Merci pour cet ajout et la pagination

**Comment by jeromecoupe** [comment]
No problem. Si tu as le temps, n'hésites pas à me donner du feedback ou à me demander ceci ou cela. Je donne un Workshop sur 11ty à l'école et ce genre de chose m'aide vraiment à peaufiner le cours.
