### ISSUE TITLE
Un exemple d'insertion d'image dans un post ?

### ISSUE THREAD

**Issue by nlebellier** [jeromecoupe/eleventy_starter#9]
Serait-ce possible ? je suis perdu dans les chemins...
Merci

**Comment by jeromecoupe** [comment]
Les chemins doivent être dans les layouts à priori. Tu as vu / lu [le contenu du workshop 11ty](https://github.com/jeromecoupe/iad_eleventy_introduction) ? Dispo en FR.

**Comment by nlebellier** [comment]
Oui j'ai vu et lu le workshop (merci pour le partage ). en fait ma question était plus sur l'insertion d'une image dans le fichier markdown plutôt que dans son entête où tu gères le chemin dans le template njk.
Donc je serai preneur d'un exemple avec une simple image appelée dans le corps d'un fichier source .md
